# Generated by Django 4.2.7 on 2023-12-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_delete_webpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='num_of_players',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
